name: Common build workflow

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    environment: dev

    steps:
    #checkout the source code from the git repo
    - uses: actions/checkout@v2

    #caches maven dependencies
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    #setup java 1.8
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    #create settings.xml file with the connected app credentials
    - name: Create settings.xml
      uses: s4u/maven-settings-action@v2.4.0
      with:
        servers: |
          [
            {
              "id": "AP-Repository",
              "username": "~~~Client~~~",
              "password": "${{ secrets.MULE_CA_CLIENTID_DEV }}~?~${{ secrets.MULE_CA_CLIENTSECRET_DEV }}"

            }
          ]

    #build a jar file and publish it to Exchange
    - name: Publish to Exchange
      run: |
        mvn clean deploy -DskipTests 